app:
  build: ./
  ports:
  - 3000:3000
  links:
  - mongo
  environment:
    MONGODB: mongodb://mongo:27017/plugins
  volumes:
  - ./:/app

mongo:
  image: mongo:3.2.3
  command: --smallfiles
  volumes:
  - ./data:/data/db